import type {
  User, JobSite, Task, TimeEntry, CheckIn,
  ChangeOrder, WorkerProfile, Alert
} from '../types'

export const MOCK_USERS: User[] = [
  {
    id: 'boss-1',
    name: 'Mike Torres',
    email: 'mike@torresco.com',
    password: 'demo123',
    role: 'boss',
    plan: 'growth',
    language: 'en',
    phone: '(555) 234-5678',
    companyName: 'Torres Construction Co.',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'worker-1',
    name: 'Carlos Rivera',
    email: 'carlos@worker.com',
    password: 'demo123',
    role: 'worker',
    plan: 'pro',
    language: 'es',
    phone: '(555) 345-6789',
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'worker-2',
    name: 'James Mitchell',
    email: 'james@worker.com',
    password: 'demo123',
    role: 'worker',
    plan: 'free',
    language: 'en',
    phone: '(555) 456-7890',
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: 'worker-3',
    name: 'Ana Souza',
    email: 'ana@worker.com',
    password: 'demo123',
    role: 'worker',
    plan: 'pro',
    language: 'pt',
    phone: '(555) 567-8901',
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'worker-4',
    name: 'Derek Johnson',
    email: 'derek@worker.com',
    password: 'demo123',
    role: 'worker',
    plan: 'free',
    language: 'en',
    phone: '(555) 678-9012',
    createdAt: '2024-03-15T00:00:00Z',
  },
  {
    id: 'worker-5',
    name: 'Marco Perez',
    email: 'marco@worker.com',
    password: 'demo123',
    role: 'worker',
    plan: 'free',
    language: 'es',
    phone: '(555) 789-0123',
    createdAt: '2024-03-20T00:00:00Z',
  },
]

export const MOCK_JOB_SITES: JobSite[] = [
  {
    id: 'site-1',
    name: 'Riverside Condos Phase 2',
    address: '1450 Riverside Dr',
    city: 'Austin',
    state: 'TX',
    bossId: 'boss-1',
    workerIds: ['worker-1', 'worker-2', 'worker-3'],
    status: 'active',
    startDate: '2024-03-01',
    endDate: '2024-07-30',
    coordinates: { lat: 30.2672, lng: -97.7431 },
    description: '48-unit residential condo complex, Phase 2 construction',
    createdAt: '2024-02-20T00:00:00Z',
  },
  {
    id: 'site-2',
    name: 'Downtown Office Remodel',
    address: '800 Congress Ave, Suite 300',
    city: 'Austin',
    state: 'TX',
    bossId: 'boss-1',
    workerIds: ['worker-4', 'worker-5'],
    status: 'active',
    startDate: '2024-04-01',
    endDate: '2024-06-15',
    coordinates: { lat: 30.2688, lng: -97.7404 },
    description: 'Full interior remodel of 3rd floor office space, 12,000 sqft',
    createdAt: '2024-03-25T00:00:00Z',
  },
  {
    id: 'site-3',
    name: 'Westlake Residence',
    address: '2200 Lakewood Dr',
    city: 'Austin',
    state: 'TX',
    bossId: 'boss-1',
    workerIds: ['worker-1', 'worker-4'],
    status: 'paused',
    startDate: '2024-01-10',
    endDate: '2024-05-30',
    coordinates: { lat: 30.2963, lng: -97.8068 },
    description: 'Custom luxury home build, 5,200 sqft',
    createdAt: '2024-01-05T00:00:00Z',
  },
]

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-1',
    jobSiteId: 'site-1',
    title: 'Install drywall — Building A Floor 3',
    description: 'Install 5/8" Type X drywall on all interior walls of units 301–312. Tape and mud included. Reference blueprints in job folder.',
    assignedTo: 'worker-1',
    assignedBy: 'boss-1',
    estimatedMinutes: 480,
    status: 'in_progress',
    priority: 'high',
    photosBefore: [],
    photosDuring: [],
    photosAfter: [],
    videoLinks: ['https://youtube.com/watch?v=drywall-install'],
    createdAt: '2024-04-10T08:00:00Z',
    startedAt: '2024-04-22T07:30:00Z',
    dueDate: '2024-04-23',
  },
  {
    id: 'task-2',
    jobSiteId: 'site-1',
    title: 'Plumbing rough-in — Units 201–206',
    description: 'Complete rough-in plumbing for units 201–206. All supply lines, drain-waste-vent stack. Coordinate with framing crew.',
    assignedTo: 'worker-2',
    assignedBy: 'boss-1',
    estimatedMinutes: 360,
    status: 'completed',
    priority: 'high',
    photosBefore: [],
    photosDuring: [],
    photosAfter: [],
    videoLinks: [],
    createdAt: '2024-04-08T08:00:00Z',
    startedAt: '2024-04-15T07:00:00Z',
    completedAt: '2024-04-15T14:30:00Z',
    dueDate: '2024-04-15',
  },
  {
    id: 'task-3',
    jobSiteId: 'site-1',
    title: 'Electrical panel installation — Main',
    description: 'Install main 400A service panel in building A mechanical room. All work per NEC 2023 code. Permit pulled, inspector visit scheduled.',
    assignedTo: 'worker-3',
    assignedBy: 'boss-1',
    estimatedMinutes: 600,
    status: 'overdue',
    priority: 'high',
    photosBefore: [],
    photosDuring: [],
    photosAfter: [],
    videoLinks: [],
    createdAt: '2024-04-09T08:00:00Z',
    dueDate: '2024-04-20',
  },
  {
    id: 'task-4',
    jobSiteId: 'site-2',
    title: 'Demolition — Existing walls',
    description: 'Demo non-load-bearing walls per marked floor plan. Protect HVAC and electrical in ceiling. Dust containment required.',
    assignedTo: 'worker-4',
    assignedBy: 'boss-1',
    estimatedMinutes: 240,
    status: 'completed',
    priority: 'medium',
    photosBefore: [],
    photosDuring: [],
    photosAfter: [],
    videoLinks: [],
    createdAt: '2024-04-05T08:00:00Z',
    startedAt: '2024-04-08T07:00:00Z',
    completedAt: '2024-04-08T12:45:00Z',
    dueDate: '2024-04-08',
  },
  {
    id: 'task-5',
    jobSiteId: 'site-2',
    title: 'Frame new conference room walls',
    description: 'Frame 4 new conference rooms per approved plans. Metal stud 3-5/8" @ 16" OC, ceiling height 9\'6".',
    assignedTo: 'worker-5',
    assignedBy: 'boss-1',
    estimatedMinutes: 480,
    status: 'pending',
    priority: 'medium',
    photosBefore: [],
    photosDuring: [],
    photosAfter: [],
    videoLinks: ['https://youtube.com/watch?v=metal-stud-framing'],
    createdAt: '2024-04-12T08:00:00Z',
    dueDate: '2024-04-26',
  },
  {
    id: 'task-6',
    jobSiteId: 'site-1',
    title: 'Paint — Building B Hallways',
    description: 'Two coats Benjamin Moore HC-172 on all hallway walls and ceilings. Prep, tape, protect floors.',
    assignedTo: 'worker-1',
    assignedBy: 'boss-1',
    estimatedMinutes: 300,
    status: 'pending',
    priority: 'low',
    photosBefore: [],
    photosDuring: [],
    photosAfter: [],
    videoLinks: [],
    createdAt: '2024-04-14T08:00:00Z',
    dueDate: '2024-04-30',
  },
]

export const MOCK_TIME_ENTRIES: TimeEntry[] = [
  {
    id: 'time-1',
    taskId: 'task-2',
    workerId: 'worker-2',
    jobSiteId: 'site-1',
    clockIn: '2024-04-15T07:00:00Z',
    clockOut: '2024-04-15T14:30:00Z',
    totalMinutes: 450,
    isOvertime: true,
  },
  {
    id: 'time-2',
    taskId: 'task-4',
    workerId: 'worker-4',
    jobSiteId: 'site-2',
    clockIn: '2024-04-08T07:00:00Z',
    clockOut: '2024-04-08T12:45:00Z',
    totalMinutes: 345,
    isOvertime: false,
  },
  {
    id: 'time-3',
    taskId: 'task-1',
    workerId: 'worker-1',
    jobSiteId: 'site-1',
    clockIn: '2024-04-22T07:30:00Z',
    totalMinutes: undefined,
    isOvertime: false,
  },
]

export const MOCK_CHECKINS: CheckIn[] = [
  {
    id: 'checkin-1',
    workerId: 'worker-1',
    jobSiteId: 'site-1',
    timestamp: '2024-04-22T07:28:00Z',
    photoUrl: '',
    location: { lat: 30.2672, lng: -97.7431, address: '1450 Riverside Dr, Austin TX' },
    verified: true,
  },
  {
    id: 'checkin-2',
    workerId: 'worker-2',
    jobSiteId: 'site-1',
    timestamp: '2024-04-22T07:45:00Z',
    photoUrl: '',
    location: { lat: 30.2671, lng: -97.7429, address: '1450 Riverside Dr, Austin TX' },
    verified: true,
  },
]

export const MOCK_CHANGE_ORDERS: ChangeOrder[] = [
  {
    id: 'co-1',
    jobSiteId: 'site-1',
    title: 'Upgrade to level 5 drywall finish',
    description: 'Owner requests Level 5 drywall finish (skim coat) in all unit hallways and common areas instead of standard Level 4. Requires additional compound and labor.',
    estimatedCost: 4200,
    status: 'approved',
    requestedBy: 'boss-1',
    createdAt: '2024-04-10T10:00:00Z',
    approvedBy: 'boss-1',
    approvedAt: '2024-04-11T09:00:00Z',
    photos: [],
  },
  {
    id: 'co-2',
    jobSiteId: 'site-2',
    title: 'Add glass partition in executive suite',
    description: 'Client wants full-height tempered glass partition with aluminum frame between exec office and reception. Not in original scope.',
    estimatedCost: 8750,
    status: 'pending',
    requestedBy: 'boss-1',
    createdAt: '2024-04-18T14:00:00Z',
    photos: [],
  },
  {
    id: 'co-3',
    jobSiteId: 'site-1',
    title: 'Relocate electrical panel — Building B',
    description: 'Structural engineer requires panel moved 6 feet east due to beam discovery. Additional conduit run required.',
    estimatedCost: 1850,
    status: 'rejected',
    requestedBy: 'boss-1',
    createdAt: '2024-04-05T11:00:00Z',
    rejectionReason: 'Awaiting revised structural drawings before approval',
    photos: [],
  },
]

export const MOCK_WORKER_PROFILES: WorkerProfile[] = [
  {
    userId: 'worker-1',
    skills: ['Drywall', 'Framing', 'Painting', 'Taping & Mudding', 'Texture'],
    certifications: [
      { id: 'cert-1', name: 'OSHA 30-Hour Construction', issuer: 'OSHA', issueDate: '2023-06-01', expiryDate: '2026-06-01', verified: true },
      { id: 'cert-2', name: 'Lead Renovation & Repair', issuer: 'EPA', issueDate: '2022-03-15', expiryDate: '2025-03-15', verified: true },
    ],
    licenses: [
      { id: 'lic-1', type: 'General Construction', number: 'TX-GC-882341', state: 'TX', expiryDate: '2025-12-31' },
    ],
    bio: '8 years drywall and interior finish experience. Bilingual English/Spanish.',
    yearsExperience: 8,
    rating: 4.8,
  },
  {
    userId: 'worker-2',
    skills: ['Plumbing', 'Rough-In', 'Finish Plumbing', 'Gas Lines', 'Irrigation'],
    certifications: [
      { id: 'cert-3', name: 'OSHA 10-Hour Construction', issuer: 'OSHA', issueDate: '2023-01-10', expiryDate: '2026-01-10', verified: true },
    ],
    licenses: [
      { id: 'lic-2', type: 'Master Plumber', number: 'TX-MP-114455', state: 'TX', expiryDate: '2025-06-30' },
    ],
    bio: 'Licensed master plumber with 12 years residential and commercial experience.',
    yearsExperience: 12,
    rating: 4.9,
  },
  {
    userId: 'worker-3',
    skills: ['Electrical', 'Panel Installation', 'Low Voltage', 'Conduit', 'Lighting'],
    certifications: [
      { id: 'cert-4', name: 'OSHA 30-Hour Construction', issuer: 'OSHA', issueDate: '2022-09-20', expiryDate: '2025-09-20', verified: true },
      { id: 'cert-5', name: 'NFPA 70E Electrical Safety', issuer: 'NFPA', issueDate: '2023-04-01', expiryDate: '2026-04-01', verified: true },
    ],
    licenses: [
      { id: 'lic-3', type: 'Master Electrician', number: 'TX-ME-772233', state: 'TX', expiryDate: '2026-01-31' },
    ],
    bio: 'Master electrician specializing in commercial panel installation and NEC compliance.',
    yearsExperience: 15,
    rating: 4.7,
  },
  {
    userId: 'worker-4',
    skills: ['Demolition', 'Framing', 'Concrete', 'Masonry', 'Heavy Equipment'],
    certifications: [
      { id: 'cert-6', name: 'OSHA 10-Hour Construction', issuer: 'OSHA', issueDate: '2024-01-15', expiryDate: '2027-01-15', verified: true },
    ],
    licenses: [],
    bio: 'Experienced in structural demo, concrete work, and rough framing.',
    yearsExperience: 6,
    rating: 4.5,
  },
  {
    userId: 'worker-5',
    skills: ['Framing', 'Metal Stud', 'Carpentry', 'Doors & Frames', 'Millwork'],
    certifications: [
      { id: 'cert-7', name: 'OSHA 10-Hour Construction', issuer: 'OSHA', issueDate: '2023-11-05', expiryDate: '2026-11-05', verified: true },
    ],
    licenses: [],
    bio: 'Specialty in metal stud framing and commercial interior carpentry.',
    yearsExperience: 9,
    rating: 4.6,
  },
]

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alert-1',
    type: 'task_overdue',
    message: 'Task "Electrical panel installation — Main" is 3 days overdue. Assigned to Ana Souza.',
    workerId: 'worker-3',
    taskId: 'task-3',
    jobSiteId: 'site-1',
    createdAt: '2024-04-23T08:00:00Z',
    read: false,
  },
  {
    id: 'alert-2',
    type: 'overtime',
    message: 'James Mitchell logged 450 min on task "Plumbing rough-in" vs 360 min estimated (+90 min).',
    workerId: 'worker-2',
    taskId: 'task-2',
    jobSiteId: 'site-1',
    createdAt: '2024-04-15T15:00:00Z',
    read: false,
  },
  {
    id: 'alert-3',
    type: 'change_order',
    message: 'Change order "Add glass partition in executive suite" pending your approval.',
    jobSiteId: 'site-2',
    createdAt: '2024-04-18T14:05:00Z',
    read: true,
  },
]
